packages = [
    "friendsofphp/php-cs-fixer",
    "pestphp/pest",
    "php-parallel-lint/php-console-highlighter",
    "php-parallel-lint/php-parallel-lint",
    "phpmd/phpmd",
    "phpstan/phpstan"
]
